# Generated by Django 4.2.9 on 2026-06-17 20:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('attendant', 'Attendant'), ('entrance_display', 'Entrance Display'), ('exit_display', 'Exit Display')], default='attendant', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sensor_id', models.CharField(help_text='Firebase key matching the ESP32 sensor node', max_length=100, unique=True)),
                ('camera_ip', models.CharField(blank=True, help_text='IP of the A9 WiFi camera on this lane', max_length=50)),
                ('servo_channel', models.IntegerField(default=0, help_text='ESP32 servo index for this gate')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sensor_id', models.CharField(max_length=100, unique=True)),
                ('servo_channel', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('firebase_node', models.CharField(blank=True, help_text='Firebase Realtime DB node path e.g. /lots/lot1', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], db_index=True, default='vacant', max_length=20)),
                ('sensor_id', models.CharField(blank=True, help_text='Firebase key for the ultrasonic sensor on this slot', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(choices=[('car', 'Normal Car'), ('truck', 'Large Truck / Van'), ('cycle', 'Motorcycle / Cycle')], max_length=20, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=0, help_text='Rate in UGX per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_max_rate', models.DecimalField(blank=True, decimal_places=0, help_text='Optional daily cap in UGX', max_digits=10, null=True)),
                ('grace_period_minutes', models.IntegerField(default=10, help_text='Free grace window before billing starts')),
                ('color_hex', models.CharField(default='#16a34a', help_text='UI badge colour for this slot type', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('van', 'Van'), ('truck', 'Truck')], max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('entry_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money (MoMo)'), ('exempt', 'Exempt / Free Pass')], max_length=20)),
                ('amount_charged', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_service_exempt', models.BooleanField(default=False)),
                ('exempt_reason', models.CharField(blank=True, help_text='e.g. KCCA, Staff, Campus Carrier', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active — Vehicle Inside'), ('paid', 'Paid & Exited'), ('exempt', 'Service Exempt'), ('void', 'Voided')], db_index=True, default='active', max_length=20)),
                ('barcode_data', models.TextField(blank=True, help_text='JSON payload encoded into QR code')),
                ('ai_classification_raw', models.JSONField(blank=True, default=dict, help_text='Raw output from Python CV model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='parking.parkingslot')),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_tickets', to=settings.AUTH_USER_MODEL)),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.entrance')),
                ('exit_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_tickets', to='parking.exit')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('mobile_money_ref', models.CharField(blank=True, help_text='MTN/Airtel reference number', max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='parking.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='parking.slottype'),
        ),
        migrations.AddField(
            model_name='exit',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='parking.parkinglot'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='parking.parkinglot'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('fire', 'Fire / Smoke'), ('lot_full', 'Parking Full'), ('section_full', 'Section Full'), ('sensor_error', 'Sensor Error'), ('gate_error', 'Gate Error')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('sensor_data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parking.parkinglot')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('lot', 'slot_number')},
        ),
        migrations.CreateModel(
            name='AudioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(choices=[('system_start', 'System Start'), ('vehicle_scan', 'Vehicle Scanning'), ('access_granted', 'Access Granted'), ('access_denied', 'Access Denied'), ('vehicle_exit', 'Vehicle Exit'), ('fire_alarm', 'Fire / Smoke Alarm'), ('lot_full', 'Parking Lot Full'), ('welcome', 'Welcome Message')], max_length=30)),
                ('track_number', models.IntegerField(help_text='DFPlayer Mini track index (1-based)')),
                ('track_filename', models.CharField(help_text='e.g. 0001.mp3', max_length=100)),
                ('volume', models.IntegerField(default=25, help_text='0–30')),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_configs', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['trigger_event'],
                'unique_together': {('lot', 'trigger_event')},
            },
        ),
        migrations.CreateModel(
            name='AttendantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.entrance')),
                ('exit_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.exit')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_assignments', to='parking.parkinglot')),
            ],
            options={
                'unique_together': {('attendant', 'lot')},
            },
        ),
    ]
