# Generated by Django 4.2.9 on 2026-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='lost_receipt_fee',
            field=models.DecimalField(decimal_places=0, default=5000, help_text='Extra fee charged when a client cannot present their original receipt (UGX)', max_digits=10),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lost_ticket_fee',
            field=models.DecimalField(decimal_places=0, default=15000, help_text="Flat fee charged when a client's ticket is completely lost and cannot be recovered in the system (UGX)", max_digits=10),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='no_plate_fee',
            field=models.DecimalField(decimal_places=0, default=10000, help_text='Flat fee for a vehicle with no ticket and no identifiable plate number (UGX)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('attendant', 'Attendant (General / Parking)'), ('entrance_attendant', 'Entrance Attendant'), ('exit_attendant', 'Exit Attendant'), ('entrance_display', 'Entrance Display'), ('exit_display', 'Exit Display')], default='attendant', max_length=20),
        ),
    ]
