# Generated by Django 4.2.9 on 2026-06-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auditlog_slottype_flat_rate_ticket_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='camera_ip',
            field=models.CharField(blank=True, help_text='IP of the camera on this lane', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='sensor_id',
            field=models.CharField(help_text='ESP32 device_id for this entrance unit', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='servo_channel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='firebase_node',
            field=models.CharField(blank=True, help_text='Legacy Firebase node path (unused for ESP32)', max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='lost_ticket_fee',
            field=models.DecimalField(decimal_places=0, default=15000, help_text="Flat fee charged when a client's ticket is completely lost (UGX)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='sensor_id',
            field=models.CharField(blank=True, help_text="ESP32 sensor_id for this slot's ultrasonic sensor", max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='parking.slottype'),
        ),
        migrations.AlterField(
            model_name='slottype',
            name='vehicle_class',
            field=models.CharField(choices=[('car', 'Normal Car'), ('truck', 'Large Truck / Van / Bus'), ('cycle', 'Motorcycle / Bicycle')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ai_classification_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='barcode_data',
            field=models.TextField(blank=True, help_text='Base64 PNG of QR code'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mobile_money_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('attendant', 'Attendant (Parking Floor)'), ('entrance_attendant', 'Entrance Attendant'), ('exit_attendant', 'Exit Attendant'), ('entrance_display', 'Entrance Display Screen'), ('exit_display', 'Exit Display Screen')], default='attendant', max_length=20),
        ),
    ]
